name: java_anotation-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build de imagem docker
      uses: docker/build-push-action@v5.2.0
      with:   
          context: ./Java_Anotacao
          file: ./Dockerfile
          push: true
          tags:
            javaanotarion:v1
            javaanotarion:latest
