name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{USER}}
        password: ${{PASSWORD}}
    
    - name: Build de imagem docker
      uses: docker/build-push-action@v5.2.0
      with:   
          context: ./Java_Anotacao/
          file: ./Java_Anotacao//Dockerfile
          push: true
          tags:
            javaanotarion:latest
            javaanotarion:v1
